name: Pull Request Label Checker
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
jobs:
  check-labels:
    name: prevent merge labels
    runs-on: ubuntu-22.04

    steps:
    - name: do-not-merge label found
      run: echo "do-not-merge label found, this PR will not be merged"; exit 1
      if: ${{ contains(github.event.*.labels.*.name, 'pr/do not merge') || contains(github.event.*.labels.*.name, 'DO NOT MERGE') }}
