name: Update test runtime statistics file for test scheduling
on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * SAT"
  push:
    branches:
      - feat/test-run-scheduler

jobs:
  process-statistics:
    name: Download statistics from GitHub and combine them
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Process statistics
        uses: Kong/gateway-test-scheduler/analyze@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          workflow-name: build_and_test.yml
          test-file-runtime-file: .ci/runtimes.json
          artifact-name-regexp: "^test-runtime-statistics-\\d+$"

      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<team-gateway@konghq.com>"
          git commit -m "chore(ci): updated test file runtime file" .ci/runtimes.json
          git push origin HEAD:chore/update-runtimes
          gh pr create --title "chore(ci): update test runtimes" \
                       --body "This PR updates the test runtimes file to incorporate latest statistics for better scheduling." \
                       --base master \
                       --head chore/update-runtimes
