name: Update test runtime statistics file for test scheduling
on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * SAT"
  # push rule below needed for testing only
  push:
    branches:
      - feat/test-run-scheduler

jobs:
  process-statistics:
    name: Download statistics from GitHub and combine them
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Process statistics
        uses: Kong/gateway-test-scheduler/analyze@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          workflow-name: build_and_test.yml
          test-file-runtime-file: .ci/runtimes.json
          artifact-name-regexp: "^test-runtime-statistics-\\d+$"

      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<team-gateway@konghq.com>"
          git commit -m "chore(ci): updated test file runtime file" .ci/runtimes.json

          FIRST_LINE=$(git diff-tree -r -c -M -C --no-commit-id HEAD | head -n 1)
          BLOB_HASH=$(echo $FIRST_LINE | awk '{print $4}')
          SIZE=$(echo $BLOB_HASH | git cat-file --batch-check | grep "blob" | awk '{ print $3 }')
          PRINTABLE_SIZE=$(numfmt --to=iec --suffix=B --format="%.1f" "$SIZE")

          git push -f origin HEAD:chore/update-runtimes
          gh pr create --title "chore(ci): update test runtimes" \
                       --body "This PR updates the test runtimes file to incorporate latest statistics for better scheduling.  It increases the repository size by $PRINTABLE_SIZE" \
                       --base master \
                       --head chore/update-runtimes
